# Generated by Django 3.1.2 on 2020-10-18 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20201013_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillanswer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
