# Generated by Django 3.1.2 on 2020-10-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20201018_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillanswer',
            name='tags',
            field=models.TextField(default='good'),
        ),
    ]
