# Generated by Django 3.1.2 on 2020-10-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skillanswer_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillanswer',
            name='tags',
        ),
    ]
