# Generated by Django 3.1.2 on 2020-10-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_remove_skillanswer_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillanswer',
            old_name='processed_answer',
            new_name='tags',
        ),
    ]
