# Generated by Django 3.1.2 on 2020-10-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_auto_20201018_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillanswer',
            name='tags',
            field=models.TextField(default='disciplined'),
        ),
    ]
