# Generated by Django 3.1.2 on 2020-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20201018_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='skillanswer',
            name='tags',
            field=models.TextField(blank=True, default='disciplined', null=True),
        ),
        migrations.AlterField(
            model_name='skillanswer',
            name='yes_or_no',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
