# Generated by Django 3.1.2 on 2020-10-13 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20201013_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolled',
            new_name='Enroll',
        ),
    ]
