# Generated by Django 3.1.2 on 2020-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201013_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='sem_type',
            field=models.CharField(choices=[('midsem', 'Mid Semester'), ('endsem', 'End Semester')], max_length=100),
        ),
    ]
