# Generated by Django 3.1.2 on 2020-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201016_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='form_name',
            field=models.CharField(default='Feedback Form', max_length=100),
        ),
    ]
