# Generated by Django 3.1.2 on 2020-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_feedbackform_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='processed_answer',
            field=models.TextField(default='heyy'),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='sentiment',
            field=models.IntegerField(default=0.4),
        ),
    ]
