# Generated by Django 3.1.2 on 2020-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201016_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='sentiment',
            field=models.FloatField(default=0.4),
        ),
    ]
