# Generated by Django 3.1.2 on 2020-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201016_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='sentiment',
            field=models.IntegerField(default=0.4),
        ),
    ]
