# Generated by Django 3.1.2 on 2020-10-19 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201016_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='time_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
