# Generated by Django 3.1.2 on 2020-10-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_formanswer_time_of_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('prof', 'Professor Feedback'), ('course', 'Course Feedback'), ('other', 'Other')], max_length=100)),
                ('sem_type', models.CharField(choices=[('midsem', 'Mid Semester'), ('endsem', 'End Semester'), ('other', 'Other')], max_length=100)),
                ('form_name', models.CharField(default='Feedback Form', max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
        ),
    ]
